version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.4
  - dependency-name: "@11ty/eleventy-plugin-rss"
    versions:
    - 1.1.0
