[build]
  command = "npm run build"
  publish = "dist"
  # functions = "./src/functions"

[context.production]
  environment = { NODE_VERSION = "10.15.3", NODE_ENV = "production" }

[dev]
  command = "npm run start"
  publish = "dist"
  port = 3000
  targetPort = 8181
  NODE_ENV = "development"
  # functionsPort = 34567

[[redirects]]
  from = "/post/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/post/"
  to = "/"
  status = 301

[[redirects]]
  from = "/blog/"
  to = "/"
  status = 301

[[redirects]]
  from = "http://jjermany.netlify.com/*"
  to = "http://jjermany.blog/:splat"
  status = 301
  force = true
